// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NHDKR4SWwNVqFUTgKe_KfSGXjRYuXi0',
    appId: '1:755553491761:web:7a288eebd6ff9d092aee10',
    messagingSenderId: '755553491761',
    projectId: 'alanocryptofx',
    authDomain: 'alanocryptofx.firebaseapp.com',
    storageBucket: 'alanocryptofx.firebasestorage.app',
    measurementId: 'G-VX1NQTLBZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZQLna30owePevgG80YtYIyNmkdGPfWs',
    appId: '1:755553491761:android:cd8bb7af12f9a2a32aee10',
    messagingSenderId: '755553491761',
    projectId: 'alanocryptofx',
    storageBucket: 'alanocryptofx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DHfhXAeHqcdx3ZgzClSn0DsmI9iC1Z4',
    appId: '1:755553491761:ios:f54e44b42bf2efe52aee10',
    messagingSenderId: '755553491761',
    projectId: 'alanocryptofx',
    storageBucket: 'alanocryptofx.firebasestorage.app',
    androidClientId: '755553491761-104atot6h03fbut33jq6r2fasgnf32sb.apps.googleusercontent.com',
    iosClientId: '755553491761-o098bmbchv42higbviki62chc174ltmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.alanoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DHfhXAeHqcdx3ZgzClSn0DsmI9iC1Z4',
    appId: '1:755553491761:ios:f54e44b42bf2efe52aee10',
    messagingSenderId: '755553491761',
    projectId: 'alanocryptofx',
    storageBucket: 'alanocryptofx.firebasestorage.app',
    androidClientId: '755553491761-104atot6h03fbut33jq6r2fasgnf32sb.apps.googleusercontent.com',
    iosClientId: '755553491761-o098bmbchv42higbviki62chc174ltmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.alanoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NHDKR4SWwNVqFUTgKe_KfSGXjRYuXi0',
    appId: '1:755553491761:web:76bf20593e2eb10f2aee10',
    messagingSenderId: '755553491761',
    projectId: 'alanocryptofx',
    authDomain: 'alanocryptofx.firebaseapp.com',
    storageBucket: 'alanocryptofx.firebasestorage.app',
    measurementId: 'G-ZV0C21XD3M',
  );
}
